[theme.options]
stealth_mode = false
fg_image = ""
bg_color = "black"
bg_image = ""
bg_anim_image = ""
font_sizes = [ 10, 8, 10, 25, 25, 9,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold"
status_font = "DejaVuSansMono"
font_awesome = ""
size_offset = 5
label_spacing = 5
cursor = "‚ù§"
friend_bars = "|"
friend_no_bars = ""
main_text_color = [ "red",]
color_mode = [ "P", "P",]
boot_animation = true
boot_min_loops = 2
boot_total_duration = 3

[theme.dev]
refresh = -1
log = "True"
debug = false

[theme.widget.channel]
position = [ 0, 0,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "CH"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.aps]
position = [ 30, 0,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "APS"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.uptime]
position = [ 190, 0,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "UP"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.line1]
position = [ 0, 10, 250, 0,]
color = [ 255,]
z_axis = 0
width = 1

[theme.widget.line2]
position = [ 0, 112, 250, 0,]
color = [ 255,]
z_axis = 0
width = 1

[theme.widget.face]
position = [ 88, 41,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = true
icon_color = true
invert = true
alpha = false
mask = true
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0

[theme.widget.friend_name]
position = [ 0, 48,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0

[theme.widget.name]
position = [ 200, 111,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0

[theme.widget.status]
position = [ 0, 11,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = true
max_length = 0

[theme.widget.shakes]
position = [ 0, 111,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "HS:"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.mode]
position = [ 0, 59,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0

[theme.widget.bluetooth]
position = [ 0, 90,]
color = [ "WHITE",]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "BT :"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.memtemp_mem]
position = [ 195, 69,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "MEM :"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.memtemp_cpu]
position = [ 195, 79,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "CPU :"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.memtemp_temp]
position = [ 195, 88,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "PI  :"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.ip1]
position = [ 0, 100,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = ""
label_font = ""
label_font_size = "Medium"
label_spacing = 0
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.feels_like]
position = [ 195, 58,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "Tmp :"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.clock1]
position = [ 100, 0,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = ""
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.clock2]
position = [ 100, 85,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = ""
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.more_uptime]
position = [ 190, 10,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0

[theme.widget.passwords]
position = [ 100, 93,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "Passes:"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.ineticon]
position = [ 195, 100,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "Inet:"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.lat]
position = [ 0, 69,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "lat:"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.lon]
position = [ 0, 79,]
color = [ 255,]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "lon:"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 1
f_awesome = false
f_awesome_size = 0

[theme.widget.connection_status]
position = [ 225, 102,]
color = [ 0,]
z_axis = 0
icon = false
invert = true
alpha = true
mask = false
refine = 150
zoom = 1
icon_color = true
